# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flyherder_gui.ui'
#
# Created: Fri Aug 31 13:28:41 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(678, 455)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.setupTab = QtGui.QWidget()
        self.setupTab.setObjectName("setupTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.setupTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_9 = QtGui.QWidget(self.setupTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.commGroupBox = QtGui.QGroupBox(self.widget_9)
        self.commGroupBox.setObjectName("commGroupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.commGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtGui.QWidget(self.commGroupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.portLineEdit = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLineEdit.sizePolicy().hasHeightForWidth())
        self.portLineEdit.setSizePolicy(sizePolicy)
        self.portLineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.portLineEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.portLineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout_2.addWidget(self.portLineEdit)
        self.connectPushButton = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.connectPushButton.setFont(font)
        self.connectPushButton.setObjectName("connectPushButton")
        self.horizontalLayout_2.addWidget(self.connectPushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.widget)
        self.verticalLayout_6.addWidget(self.commGroupBox)
        self.paramGroupBox = QtGui.QGroupBox(self.widget_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramGroupBox.sizePolicy().hasHeightForWidth())
        self.paramGroupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.paramGroupBox.setFont(font)
        self.paramGroupBox.setObjectName("paramGroupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.paramGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtGui.QWidget(self.paramGroupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.boundsCheckBox = QtGui.QCheckBox(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boundsCheckBox.sizePolicy().hasHeightForWidth())
        self.boundsCheckBox.setSizePolicy(sizePolicy)
        self.boundsCheckBox.setChecked(True)
        self.boundsCheckBox.setObjectName("boundsCheckBox")
        self.horizontalLayout_10.addWidget(self.boundsCheckBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.paramGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_2 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.moveSpeedLineEdit = QtGui.QLineEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveSpeedLineEdit.sizePolicy().hasHeightForWidth())
        self.moveSpeedLineEdit.setSizePolicy(sizePolicy)
        self.moveSpeedLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.moveSpeedLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.moveSpeedLineEdit.setFont(font)
        self.moveSpeedLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.moveSpeedLineEdit.setObjectName("moveSpeedLineEdit")
        self.horizontalLayout_15.addWidget(self.moveSpeedLineEdit)
        self.label_5 = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_15.addWidget(self.label_5)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.label_3 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_15.addWidget(self.label_3)
        self.xSepLineEdit = QtGui.QLineEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xSepLineEdit.sizePolicy().hasHeightForWidth())
        self.xSepLineEdit.setSizePolicy(sizePolicy)
        self.xSepLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.xSepLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.xSepLineEdit.setFont(font)
        self.xSepLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xSepLineEdit.setObjectName("xSepLineEdit")
        self.horizontalLayout_15.addWidget(self.xSepLineEdit)
        self.label_7 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtGui.QWidget(self.paramGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_6 = QtGui.QLabel(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_16.addWidget(self.label_6)
        self.homeSpeedLineEdit = QtGui.QLineEdit(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeSpeedLineEdit.sizePolicy().hasHeightForWidth())
        self.homeSpeedLineEdit.setSizePolicy(sizePolicy)
        self.homeSpeedLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.homeSpeedLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.homeSpeedLineEdit.setFont(font)
        self.homeSpeedLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.homeSpeedLineEdit.setObjectName("homeSpeedLineEdit")
        self.horizontalLayout_16.addWidget(self.homeSpeedLineEdit)
        self.label_17 = QtGui.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.RichText)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.label_4 = QtGui.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_16.addWidget(self.label_4)
        self.ySepLineEdit = QtGui.QLineEdit(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ySepLineEdit.sizePolicy().hasHeightForWidth())
        self.ySepLineEdit.setSizePolicy(sizePolicy)
        self.ySepLineEdit.setMinimumSize(QtCore.QSize(70, 0))
        self.ySepLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.ySepLineEdit.setFont(font)
        self.ySepLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ySepLineEdit.setObjectName("ySepLineEdit")
        self.horizontalLayout_16.addWidget(self.ySepLineEdit)
        self.label_15 = QtGui.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.label_15.setFont(font)
        self.label_15.setTextFormat(QtCore.Qt.RichText)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.stepsWidget_6 = QtGui.QWidget(self.paramGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepsWidget_6.sizePolicy().hasHeightForWidth())
        self.stepsWidget_6.setSizePolicy(sizePolicy)
        self.stepsWidget_6.setObjectName("stepsWidget_6")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.stepsWidget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtGui.QLabel(self.stepsWidget_6)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        spacerItem6 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.label_34 = QtGui.QLabel(self.stepsWidget_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setTextFormat(QtCore.Qt.PlainText)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_3.addWidget(self.label_34)
        self.orientCheckBox_0 = QtGui.QCheckBox(self.stepsWidget_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.orientCheckBox_0.setFont(font)
        self.orientCheckBox_0.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.orientCheckBox_0.setText("")
        self.orientCheckBox_0.setChecked(True)
        self.orientCheckBox_0.setObjectName("orientCheckBox_0")
        self.horizontalLayout_3.addWidget(self.orientCheckBox_0)
        self.label_20 = QtGui.QLabel(self.stepsWidget_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.PlainText)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        self.orientCheckBox_1 = QtGui.QCheckBox(self.stepsWidget_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.orientCheckBox_1.setFont(font)
        self.orientCheckBox_1.setText("")
        self.orientCheckBox_1.setChecked(True)
        self.orientCheckBox_1.setObjectName("orientCheckBox_1")
        self.horizontalLayout_3.addWidget(self.orientCheckBox_1)
        self.label_13 = QtGui.QLabel(self.stepsWidget_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.orientCheckBox_2 = QtGui.QCheckBox(self.stepsWidget_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.orientCheckBox_2.setFont(font)
        self.orientCheckBox_2.setText("")
        self.orientCheckBox_2.setObjectName("orientCheckBox_2")
        self.horizontalLayout_3.addWidget(self.orientCheckBox_2)
        self.label_21 = QtGui.QLabel(self.stepsWidget_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.PlainText)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_3.addWidget(self.label_21)
        self.orientCheckBox_3 = QtGui.QCheckBox(self.stepsWidget_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.orientCheckBox_3.setFont(font)
        self.orientCheckBox_3.setText("")
        self.orientCheckBox_3.setObjectName("orientCheckBox_3")
        self.horizontalLayout_3.addWidget(self.orientCheckBox_3)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_3.addWidget(self.stepsWidget_6)
        self.verticalLayout_6.addWidget(self.paramGroupBox)
        spacerItem8 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.verticalLayout_2.addWidget(self.widget_9)
        self.tabWidget.addTab(self.setupTab, "")
        self.controlTab = QtGui.QWidget()
        self.controlTab.setObjectName("controlTab")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.controlTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_7 = QtGui.QWidget(self.controlTab)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pwrCheckBox = QtGui.QCheckBox(self.widget_7)
        self.pwrCheckBox.setEnabled(True)
        self.pwrCheckBox.setChecked(False)
        self.pwrCheckBox.setObjectName("pwrCheckBox")
        self.horizontalLayout.addWidget(self.pwrCheckBox)
        spacerItem9 = QtGui.QSpacerItem(457, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout_8.addWidget(self.widget_7)
        self.widget_6 = QtGui.QWidget(self.controlTab)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.moveGroupBox = QtGui.QGroupBox(self.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveGroupBox.sizePolicy().hasHeightForWidth())
        self.moveGroupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.moveGroupBox.setFont(font)
        self.moveGroupBox.setObjectName("moveGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.moveGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stepsWidget_5 = QtGui.QWidget(self.moveGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepsWidget_5.sizePolicy().hasHeightForWidth())
        self.stepsWidget_5.setSizePolicy(sizePolicy)
        self.stepsWidget_5.setObjectName("stepsWidget_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.stepsWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_35 = QtGui.QLabel(self.stepsWidget_5)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setTextFormat(QtCore.Qt.PlainText)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_5.addWidget(self.label_35)
        self.posLineEdit_0 = QtGui.QLineEdit(self.stepsWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posLineEdit_0.sizePolicy().hasHeightForWidth())
        self.posLineEdit_0.setSizePolicy(sizePolicy)
        self.posLineEdit_0.setMinimumSize(QtCore.QSize(100, 0))
        self.posLineEdit_0.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.posLineEdit_0.setFont(font)
        self.posLineEdit_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.posLineEdit_0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.posLineEdit_0.setObjectName("posLineEdit_0")
        self.horizontalLayout_5.addWidget(self.posLineEdit_0)
        spacerItem10 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.label_22 = QtGui.QLabel(self.stepsWidget_5)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setTextFormat(QtCore.Qt.PlainText)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.posLineEdit_1 = QtGui.QLineEdit(self.stepsWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posLineEdit_1.sizePolicy().hasHeightForWidth())
        self.posLineEdit_1.setSizePolicy(sizePolicy)
        self.posLineEdit_1.setMinimumSize(QtCore.QSize(100, 0))
        self.posLineEdit_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.posLineEdit_1.setFont(font)
        self.posLineEdit_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.posLineEdit_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.posLineEdit_1.setObjectName("posLineEdit_1")
        self.horizontalLayout_5.addWidget(self.posLineEdit_1)
        spacerItem11 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.label_24 = QtGui.QLabel(self.stepsWidget_5)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setTextFormat(QtCore.Qt.PlainText)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        self.posLineEdit_2 = QtGui.QLineEdit(self.stepsWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posLineEdit_2.sizePolicy().hasHeightForWidth())
        self.posLineEdit_2.setSizePolicy(sizePolicy)
        self.posLineEdit_2.setMinimumSize(QtCore.QSize(100, 0))
        self.posLineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.posLineEdit_2.setFont(font)
        self.posLineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.posLineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.posLineEdit_2.setObjectName("posLineEdit_2")
        self.horizontalLayout_5.addWidget(self.posLineEdit_2)
        spacerItem12 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.label_23 = QtGui.QLabel(self.stepsWidget_5)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setTextFormat(QtCore.Qt.PlainText)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23)
        self.posLineEdit_3 = QtGui.QLineEdit(self.stepsWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posLineEdit_3.sizePolicy().hasHeightForWidth())
        self.posLineEdit_3.setSizePolicy(sizePolicy)
        self.posLineEdit_3.setMinimumSize(QtCore.QSize(100, 0))
        self.posLineEdit_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.posLineEdit_3.setFont(font)
        self.posLineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.posLineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.posLineEdit_3.setObjectName("posLineEdit_3")
        self.horizontalLayout_5.addWidget(self.posLineEdit_3)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.verticalLayout.addWidget(self.stepsWidget_5)
        self.widget_10 = QtGui.QWidget(self.moveGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.movePushButton = QtGui.QPushButton(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.movePushButton.setFont(font)
        self.movePushButton.setObjectName("movePushButton")
        self.horizontalLayout_8.addWidget(self.movePushButton)
        self.label_9 = QtGui.QLabel(self.widget_10)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.verticalLayout.addWidget(self.widget_10)
        self.verticalLayout_7.addWidget(self.moveGroupBox)
        self.positionGroupBox = QtGui.QGroupBox(self.widget_6)
        self.positionGroupBox.setObjectName("positionGroupBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.positionGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stepsWidget_7 = QtGui.QWidget(self.positionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepsWidget_7.sizePolicy().hasHeightForWidth())
        self.stepsWidget_7.setSizePolicy(sizePolicy)
        self.stepsWidget_7.setObjectName("stepsWidget_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.stepsWidget_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_36 = QtGui.QLabel(self.stepsWidget_7)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setTextFormat(QtCore.Qt.PlainText)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_6.addWidget(self.label_36)
        self.posLabel_0 = QtGui.QLabel(self.stepsWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posLabel_0.sizePolicy().hasHeightForWidth())
        self.posLabel_0.setSizePolicy(sizePolicy)
        self.posLabel_0.setMinimumSize(QtCore.QSize(100, 27))
        self.posLabel_0.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.posLabel_0.setFont(font)
        self.posLabel_0.setAutoFillBackground(False)
        self.posLabel_0.setStyleSheet(".QLabel{\n"
"background-color: #999;\n"
"}")
        self.posLabel_0.setFrameShape(QtGui.QFrame.Box)
        self.posLabel_0.setFrameShadow(QtGui.QFrame.Sunken)
        self.posLabel_0.setText("")
        self.posLabel_0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.posLabel_0.setObjectName("posLabel_0")
        self.horizontalLayout_6.addWidget(self.posLabel_0)
        spacerItem15 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.label_25 = QtGui.QLabel(self.stepsWidget_7)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setTextFormat(QtCore.Qt.PlainText)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_6.addWidget(self.label_25)
        self.posLabel_1 = QtGui.QLabel(self.stepsWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posLabel_1.sizePolicy().hasHeightForWidth())
        self.posLabel_1.setSizePolicy(sizePolicy)
        self.posLabel_1.setMinimumSize(QtCore.QSize(100, 27))
        self.posLabel_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.posLabel_1.setFont(font)
        self.posLabel_1.setAutoFillBackground(False)
        self.posLabel_1.setStyleSheet(".QLabel{\n"
"background-color: #999;\n"
"}")
        self.posLabel_1.setFrameShape(QtGui.QFrame.Box)
        self.posLabel_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.posLabel_1.setText("")
        self.posLabel_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.posLabel_1.setObjectName("posLabel_1")
        self.horizontalLayout_6.addWidget(self.posLabel_1)
        spacerItem16 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.label_26 = QtGui.QLabel(self.stepsWidget_7)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setTextFormat(QtCore.Qt.PlainText)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_6.addWidget(self.label_26)
        self.posLabel_2 = QtGui.QLabel(self.stepsWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posLabel_2.sizePolicy().hasHeightForWidth())
        self.posLabel_2.setSizePolicy(sizePolicy)
        self.posLabel_2.setMinimumSize(QtCore.QSize(100, 27))
        self.posLabel_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.posLabel_2.setFont(font)
        self.posLabel_2.setAutoFillBackground(False)
        self.posLabel_2.setStyleSheet(".QLabel{\n"
"background-color: #999;\n"
"}")
        self.posLabel_2.setFrameShape(QtGui.QFrame.Box)
        self.posLabel_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.posLabel_2.setText("")
        self.posLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.posLabel_2.setObjectName("posLabel_2")
        self.horizontalLayout_6.addWidget(self.posLabel_2)
        spacerItem17 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.label_27 = QtGui.QLabel(self.stepsWidget_7)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setTextFormat(QtCore.Qt.PlainText)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_6.addWidget(self.label_27)
        self.posLabel_3 = QtGui.QLabel(self.stepsWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posLabel_3.sizePolicy().hasHeightForWidth())
        self.posLabel_3.setSizePolicy(sizePolicy)
        self.posLabel_3.setMinimumSize(QtCore.QSize(100, 27))
        self.posLabel_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        self.posLabel_3.setFont(font)
        self.posLabel_3.setAutoFillBackground(False)
        self.posLabel_3.setStyleSheet(".QLabel{\n"
"background-color: #999;\n"
"}")
        self.posLabel_3.setFrameShape(QtGui.QFrame.Box)
        self.posLabel_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.posLabel_3.setText("")
        self.posLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.posLabel_3.setObjectName("posLabel_3")
        self.horizontalLayout_6.addWidget(self.posLabel_3)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.verticalLayout_5.addWidget(self.stepsWidget_7)
        self.widget_5 = QtGui.QWidget(self.positionGroupBox)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.homePushButton = QtGui.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.homePushButton.setFont(font)
        self.homePushButton.setObjectName("homePushButton")
        self.horizontalLayout_12.addWidget(self.homePushButton)
        self.stopPushButton = QtGui.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.stopPushButton.setFont(font)
        self.stopPushButton.setObjectName("stopPushButton")
        self.horizontalLayout_12.addWidget(self.stopPushButton)
        spacerItem19 = QtGui.QSpacerItem(364, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem19)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.verticalLayout_7.addWidget(self.positionGroupBox)
        spacerItem20 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem20)
        self.verticalLayout_8.addWidget(self.widget_6)
        self.tabWidget.addTab(self.controlTab, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.actionLicense = QtGui.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.actionUsage = QtGui.QAction(MainWindow)
        self.actionUsage.setObjectName("actionUsage")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "FlyHerder Demo GUI v1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.commGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Communication", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Serial Port", None, QtGui.QApplication.UnicodeUTF8))
        self.connectPushButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.paramGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.boundsCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Bound Check", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Move Speed ", None, QtGui.QApplication.UnicodeUTF8))
        self.moveSpeedLineEdit.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "1&ndash;90 [mm/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Separation (x-axis)", None, QtGui.QApplication.UnicodeUTF8))
        self.xSepLineEdit.setText(QtGui.QApplication.translate("MainWindow", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "[mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Home Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.homeSpeedLineEdit.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "1&ndash;90 [mm/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Separation (y-axis)", None, QtGui.QApplication.UnicodeUTF8))
        self.ySepLineEdit.setText(QtGui.QApplication.translate("MainWindow", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "[mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Axis Orientation (check to reverse) ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "X0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Y0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "X1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Y1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setupTab), QtGui.QApplication.translate("MainWindow", "Device Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.pwrCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Drive Power", None, QtGui.QApplication.UnicodeUTF8))
        self.moveGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Move To Position [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "X0 ", None, QtGui.QApplication.UnicodeUTF8))
        self.posLineEdit_0.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Y0", None, QtGui.QApplication.UnicodeUTF8))
        self.posLineEdit_1.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "X1", None, QtGui.QApplication.UnicodeUTF8))
        self.posLineEdit_2.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Y1", None, QtGui.QApplication.UnicodeUTF8))
        self.posLineEdit_3.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.movePushButton.setText(QtGui.QApplication.translate("MainWindow", "Move", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Note, the system must be homed ", None, QtGui.QApplication.UnicodeUTF8))
        self.positionGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Current Position [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "X0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Y0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "X1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Y1", None, QtGui.QApplication.UnicodeUTF8))
        self.homePushButton.setText(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.stopPushButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controlTab), QtGui.QApplication.translate("MainWindow", "Motion Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicense.setText(QtGui.QApplication.translate("MainWindow", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUsage.setText(QtGui.QApplication.translate("MainWindow", "Usage", None, QtGui.QApplication.UnicodeUTF8))

